#!/bin/zsh

if [ -f /opt/homebrew/bin/ghidraRun ] && [ -x /opt/homebrew/bin/ghidraRun ]; then
  /opt/homebrew/bin/ghidraRun
elif [ -f /usr/local/bin/ghidraRun ] && [ -x /usr/local/bin/ghidraRun ]; then
	/usr/local/bin/ghidraRun
else
	osascript -e 'tell app "System Events" to display alert "Unable to find Homebrew-managed Ghidra installation."'
fi

